"""empty message

Revision ID: 76af2cea21f5
Revises: a6b1a87b6eba
Create Date: 2020-06-21 01:11:43.822385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76af2cea21f5'
down_revision = 'a6b1a87b6eba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
