"""empty message

Revision ID: e2cbc90a82ed
Revises: edd1eaeef335
Create Date: 2020-06-23 19:58:59.504016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2cbc90a82ed'
down_revision = 'edd1eaeef335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todolists SET completed = False WHERE completed IS NULL;')
    op.alter_column('todolists', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
